services:

  api:
    build: api/
    ports:
      - "8000:8000"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.6
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
     - ./data/mariadb:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
    ports:
      - 8001:80
    
