services:

  api:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - mariadb

  analyzer:
    build: ./analyzer
    depends_on:
      - api

  mariadb:
    image: mariadb:10.6
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
     - ./data/mariadb:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
    ports:
      - 8001:80

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
    environment:
      DOZZLE_ENABLE_ACTIONS: "true"

    
